; Instructions to obtain client_id and client_secret:
;
; 1. Registration: Sign up at Copernicus Data Space Ecosystem (https://dataspace.copernicus.eu/explore-data/data-collections/copernicus-contributing-missions/collections-description/COP-DEM)
; 2. API Credentials: After registration, create an OAuth client to obtain your client_id and client_secret

[CopernicusAPI]
client_id = YOUR_CLIENT_ID
client_secret = YOUR_CLIENT_SECRET